<?php
$productos = [
    [
        "id" => 1,
        "titulo" => "EA Sports FC 26",
        "cover" => "assets/img/covers/fc26.jpg",
        "platform_icon" => "assets/img/platforms/steam.png",
        "platform_alt" => "Steam",
        "platform" => "steam",
        "discount" => "-30%",
        "price" => "39.99€",
        "genero" => "Deportes",
        "modo" => "Singleplayer / Multijugador Online",
        "descripcion" => "La próxima evolución del fútbol con mecánicas renovadas, física mejorada y experiencias competitivas online y offline.",
        "details_url" => "detalles.php",
        "add_url" => "carrito.php"
    ],
    [
        "id" => 2,
        "titulo" => "EA Sports FC 25",
        "cover" => "assets/img/covers/fc25.jpeg",
        "platform_icon" => "assets/img/platforms/steam.png",
        "platform_alt" => "Steam",
        "platform" => "steam",
        "discount" => "-10%",
        "price" => "49.99€",
        "genero" => "Deportes",
        "modo" => "Singleplayer / Multijugador Online",
        "descripcion" => "Fútbol con nuevas animaciones, modos renovados y mejoras de jugabilidad orientadas al competitivo.",
        "details_url" => "detalles.php",
        "add_url" => "carrito.php"
    ],
    [
        "id" => 3,
        "titulo" => "God of War Ragnarök",
        "cover" => "assets/img/covers/gow-ragnarok.jpg",
        "platform_icon" => "assets/img/platforms/playstation.png",
        "platform_alt" => "PlayStation",
        "platform" => "playstation",
        "discount" => "-25%",
        "price" => "44.99€",
        "genero" => "Acción / Aventura",
        "modo" => "Singleplayer",
        "descripcion" => "Kratos y Atreus se enfrentan al Ragnarök en una aventura épica por los nueve reinos.",
        "details_url" => "detalles.php",
        "add_url" => "carrito.php"
    ],
    [
        "id" => 4,
        "titulo" => "The Last of Us Part I",
        "cover" => "assets/img/covers/tlou-part1.jpg",
        "platform_icon" => "assets/img/platforms/playstation.png",
        "platform_alt" => "PlayStation",
        "platform" => "playstation",
        "discount" => "-15%",
        "price" => "59.99€",
        "genero" => "Acción / Aventura",
        "modo" => "Singleplayer",
        "descripcion" => "Una versión modernizada del clásico con mejoras gráficas, de IA y de accesibilidad.",
        "details_url" => "detalles.php",
        "add_url" => "carrito.php"
    ],
    [
        "id" => 5,
        "titulo" => "Halo Infinite",
        "cover" => "assets/img/covers/halo-infinite.jpeg",
        "platform_icon" => "assets/img/platforms/xbox.png",
        "platform_alt" => "Xbox",
        "platform" => "xbox",
        "discount" => "-40%",
        "price" => "29.99€",
        "genero" => "Shooter",
        "modo" => "Singleplayer / Multijugador Online",
        "descripcion" => "El Jefe Maestro regresa con campaña y multijugador para combates de arena.",
        "details_url" => "detalles.php",
        "add_url" => "carrito.php"
    ],
    [
        "id" => 6,
        "titulo" => "Forza Horizon 5",
        "cover" => "assets/img/covers/forza-horizon-5.jpeg",
        "platform_icon" => "assets/img/platforms/xbox.png",
        "platform_alt" => "Xbox",
        "platform" => "xbox",
        "discount" => "-20%",
        "price" => "47.99€",
        "genero" => "Carreras",
        "modo" => "Singleplayer / Multijugador Online",
        "descripcion" => "Festival de conducción en mundo abierto con cientos de coches y eventos en México.",
        "details_url" => "detalles.php",
        "add_url" => "carrito.php"
    ],
    [
        "id" => 7,
        "titulo" => "The Legend of Zelda: Tears of the Kingdom",
        "cover" => "assets/img/covers/zelda-totk.jpeg",
        "platform_icon" => "assets/img/platforms/nintendo.png",
        "platform_alt" => "Nintendo Switch",
        "platform" => "nintendo",
        "discount" => "-5%",
        "price" => "64.99€",
        "genero" => "Aventura",
        "modo" => "Singleplayer",
        "descripcion" => "Explora Hyrule y los cielos con nuevas habilidades y construcción de artefactos.",
        "details_url" => "detalles.php",
        "add_url" => "carrito.php"
    ],
    [
        "id" => 8,
        "titulo" => "Super Mario Bros. Wonder",
        "cover" => "assets/img/covers/mario-wonder.jpg",
        "platform_icon" => "assets/img/platforms/nintendo.png",
        "platform_alt" => "Nintendo Switch",
        "platform" => "nintendo",
        "discount" => "-15%",
        "price" => "54.99€",
        "genero" => "Plataformas",
        "modo" => "Singleplayer / Multijugador Local",
        "descripcion" => "Nueva aventura 2D con flores maravilla, niveles creativos y cooperativo.",
        "details_url" => "detalles.php",
        "add_url" => "carrito.php"
    ]
];
